### ISSUE TITLE
/mail recipient invocation

### ISSUE THREAD

**Issue by Montandalar** [mt-mods/mail#101]
Hi, this mail mod fork is looking nice. I always wanted an outbox and this seems to have it.

I wanted to request a feature that I've always wanted; maybe I will write it later if you would agree it's a good idea. I would like there to be a recipient argument available for /mail that will open the compose formspec with the recipient pre-filled with the argument. So

`/mail Blockhead`

Would become a valid way to start composing mail to the player _Blockhead_. This formalises a common phrase I've seen written on signs, where people invite others to mail them to get contact:

> Blah Blah Blah.. Any problems, /mail Blockhead

Which intuitively tells me that I should include the argument "Blockhead" and not just that the argument would be ignored.

Thoughts? Disagreements? Or do you agree it's a good idea? Let me know :)

**Comment by Athozus** [comment]
Very good, I can do that easily. I think adding a subject or a body would be harder because it requires separating the content in an inline field but a model list set up by players could be something interesting for 1.3.0. Anyway, I will make that feature quickly. Thanks for submitting this ;)

**Comment by Athozus** [comment]
Hope, this is done !
