### ISSUE TITLE
Message ID mess

### ISSUE THREAD

**Issue by singularis-mzf** [mt-mods/mail#135]
When a single message in inbox is selected and a new message is created, the new message will take an ID of the selected message, which causes multiple kind of wierd behaviour when the new message is sent like:

* When the message is sent, the original message (even completely unrelated) disappers from the inbox.
* When the selected message has multiple to-players and reply-all function has been used on it, the reply message will have the same ID as the original message which will cause conflicts in inboxes of other recipients who already have the original message there (they will not be able to select one of the messages independently).
* And so on...

The cause is this newly added code in mail/ui/compose.lua:

```
if mail.selected_idxs.message[name] then
    id = mail.selected_idxs.message[name]
end
````

There is a code in mail.show_compose() that tries to save the id for the message, but if the id parameter is nil (which it is in most of the cases), the original id of the originally selected message is preserved. Maybe to generate a new ID in mail.show_compose() instead of waiting for a callback will help.

**Comment by BuckarooBanzay** [comment]
I'll try to address this next time i feel like working on this mod, PR's are always open by the way :wink:

**Comment by Athozus** [comment]
We have problems with message IDs since the last release, I will make an utility to fix the storage, and it will certainly fix many bugs at once. Thanks anyway for reporting :+1:
