### ISSUE TITLE
Security: Prevent players from sharing a mailbox

### ISSUE THREAD

**Issue by PeterNerlich** [mt-mods/mail#2]
If my assumption is correct that I can log in with any account and then log in with an account with the same name but containing a slash (`/`) or a dot (`.`) and minetest treats it as two different players, then we have a gaping security hole, [because this mod loads the same JSON file for all of them (storage.lua:5)](https://github.com/minetest-mail/mail_mod/blob/2d087eaa139d77337819331ce754344692ff9282/storage.lua#L5).

To avoid problems with file systems and directories, dots and slashes are stripped from the player name before taking it as the file name to load or create for mail storage. **Uncountably infinite accounts can be created** by appending any of the stripped symbols anywhere in the name any number of times **to get a different player that still has access to the same mail data**.

**PROPOSITION:** Adjust logic in `getMailFile()` such that all possible player names are in a one-to-one relation with their assigned `saneplayername` by

- just using a hash function like SHA1 or
- escaping all special symbols or
- escaping just the offending special symbols.

**Comment by BuckarooBanzay** [comment]
Good thinking, but you can't login with a `.` or `/` character in your username (i just re-checked again :smile:).
So the account-takeover _should_ be impossible...
Or did i miss something else there? :thinking:

**Comment by PeterNerlich** [comment]
Okay, that is comforting. Yes I didn't try it or research whether it was possible. I do not follow the development dynamics of minetest, how likely is it for this to change (or maybe for someone to compile their own version to allow more chars, besides other stuff)?
Git blame says the line was last touched 9 years ago, when it occoured in a different place and got `.,` removed (so this would have been possible before). That line had been introduced a year earlier, with a commit ["[...] Also now players are saved on disk."](https://github.com/minetest/minetest/commit/64b59757322e29c331c0a75262baec4382673e6f).

So overall, my suspicion says it is well beyond the threshold of unlikely I would freak out about. But then again, the solution does not seem complicated. The migration code it would require might be the hardest part.

**Comment by PeterNerlich** [comment]
Is it a desired feature to have the mail files named plainly like their corresponding player or was that just convenience while writing something that works? In that case I would just go for the hash solution and call it sufficiently future proof.

**Comment by BuckarooBanzay** [comment]
> Is it a desired feature to have the mail files named plainly like their corresponding player or was that just convenience while writing something that works? In that case I would just go for the hash solution and call it sufficiently future proof.

That was mostly convenience, hashing the playername does sound like a proper solution, altough the _best_ solution would be to store that data in a database and not as files on disk.
I'm not aware of a portable, lua-only database solution but i'm open for suggestions...

The switch to hashed filenames needs some migration code, i haven't checked the numbers on my servers but that may cause some initial startup delays (just once though).

**Comment by Athozus** [comment]
Should be fixed with v3 storage, using `mod_storage/` directory and `"player"` syntax. If not, please re-open.
