### ISSUE TITLE
Pressing Esc button leads to i button not bringing uop inv anymore

### ISSUE THREAD

**Issue by Bastrabun** [mt-mods/mail#20]
Repro:

> unified_inventory and mail_mod active
1. Open a single mail (regardless of old/new)
2. Press Esc button
3. Press i button
=> Inventory doesn't come up again.

Default inv does not have the problem, but unified inventory has.

For my reference 1818

**Comment by BuckarooBanzay** [comment]
Yeah, that's a known bug and i _think_ i added a workaround that fixes that in a `minetest.after` call, if you wait one or two seconds it should work again :shrug: 

That said: this is an ancient code-base, there are better ways now to display a simple formspec, PR's welcome :D
