### ISSUE TITLE
Trash directory

### ISSUE THREAD

**Issue by Athozus** [mt-mods/mail#38]
Add a trash directory then :

1. From Inbox/Outbox -> Click on delete
2. Message goes to Trash
3. Trash -> Click on delete
4. Message permanently deleted

**Comment by S-S-X** [comment]
I think trash can like that should delete messages automatically after few days / weeks unless restored.

And then my personal preference would be that when I hit "delete" then message is really deleted immediately, not just moved somewhere. I guess there's others who would also like to have this behavior so maybe there should be 2 buttons or per player configuration?

**Comment by Athozus** [comment]
> I think trash can like that should delete messages automatically after few days / weeks unless restored.
> 
> If not deleted automatically then it should be called "archive" instead.

Yes, auto-archiving and archiving goes to admins storage.

> And then my personal preference would be that when I hit "delete" then message is really deleted immediately, not just moved somewhere. I guess there's others who would also like to have this behavior so maybe there should be 2 buttons or per player configuration?

You're right, me too I dislike the auto-trash on computers :P, so I'll set up a setting.

**Comment by S-S-X** [comment]
> You're right, me too I dislike the auto-trash on computers :P, so I'll set up a setting.

For this I think it might be appropriate to use player metadata for configuration, just prefix keys with mod name to avoid possible conflicts.

Of course another option is to use JSON files but I have a feeling that player meta would be better choice.
