### ISSUE TITLE
Add settings

### ISSUE THREAD

**Issue by Athozus** [mt-mods/mail#51]
- [ ] Receive notifications
- [ ] Show unread messages in different color
- [ ] Show cc/bcc messages in different color

+ S-S-X Suggestions

* [ ] Message deletion behavior #38
* [ ] Fields shown in message lists
* [ ] Default sorting field and default sort direction
* [ ] Sounds / other notifications?

+ New settings proposals

* [ ] Enable HUD

**Comment by S-S-X** [comment]
* [ ] Message deletion behavior #38
* [ ] Fields shown in message lists
* [ ] Default sorting field and default sort direction

**Comment by Athozus** [comment]
I tried a first layout for the settings (the backend is not yet implemented), if you have any objections / ideas / feedbacks.
![screenshot_20230503_225255](https://user-images.githubusercontent.com/75171564/236047256-3f278398-59f3-496c-9c6c-fa16c54bc778.png)
