### ISSUE TITLE
Close button doesn't close the formspec

### ISSUE THREAD

**Issue by Bastrabun** [mt-mods/mail#63]
MT client 5.8.0-dev server 5.6.1 , mial_mod 911c0134cf2ba29cc17f26a2e2763b5726f1fdf3

Apart from that: THANK YOU VERY MUCH for all the effort :)

For my reference 4173

**Comment by S-S-X** [comment]
My guess is that, technically  speaking, it actually closes formspec but opens it again immediately after.
Probably just needs check for quit event and prevent any attempts to refresh formspec here (just return immediately):
https://github.com/mt-mods/mail/blob/67bda9a788f96dfcc6b6a421445d023fb6dbe5f8/ui/events.lua#L13-L16

**Comment by Athozus** [comment]
Hey, on what page are you ? inbox/outbox/message view/etc... ?

@S-S-X is right, I tried it many times and finally I had two of that, and I think following could fix the issue :

```lua
if formname ~= "mail:inbox" and formname ~= "mail:sent" and formname ~= "mail:drafts" then
    return
elseif fields.quit then
    return
end
```
