### ISSUE TITLE
Allow multiple drafts or show warning before removing previous

### ISSUE THREAD

**Issue by S-S-X** [mt-mods/mail#92]
Reported issue at pandorbox #reports channel:

> "save draft" feature currently only allows one draft per sender and appears to silently overwrite/delete any formerly added drafts (even to different recipient)

**Comment by Athozus** [comment]
You're talking about drafts that are in the tab ? There are several drafts, I tried many things and a new is always created, no replacements. I close cause it's totally working (until further notice), maybe a mail version which is not stable.

**Comment by S-S-X** [comment]
Was 9679251 according to https://github.com/pandorabox-io/pandorabox-mods (so commit just before delete loop fixes [Fix half deletion of messages](https://github.com/mt-mods/mail/commit/5e24b9274feff70ba584a5b4592bc048ed47fea9))
I guess have to ask for more information, delete fix shouldn't affect this right?

**Comment by Athozus** [comment]
I logged on Pandorabox and nothing was troubled, I still don't know why. Apparently it happens for only one user, so I close until more reports or a fix. I don't think it's really from mail there.
