### ISSUE TITLE
deleting multiple mails is bugged

### ISSUE THREAD

**Issue by fluxionary** [mt-mods/mail#94]
if you "select all" and click "delete", only half of the messages are deleted.

if you select a number of messages manually and click "delete", messages that were not selected may be deleted.

**Comment by Athozus** [comment]
Yeah @fluxionary we're reported this on Discord, it is due to the basic `table.remove()` which can becomes bugged quickly. We're trying to fix that (with @S-S-X).

**Comment by Athozus** [comment]
Both are fixed now @fluxionary, thx for reporting btw (5e24b92)
