### ISSUE TITLE
Ading drafts does not always work

### ISSUE THREAD

**Issue by FeXoR-o-Illuria** [mt-mods/mail#96]
What I did:
- Create a draft
- Create a second draft with different title
- Select the second draft and edit it to be identical
- Create a new draft -> The selected draft was edited instead of a new one added.
- Delete all drafts
- Create a new draft
- Multiple attempts to create a new second draft -> The existing draft was changed instead of a new one added

I suspect it either to be the selection never gets dropped or the list got missformed by 2 identical drafts.

**Comment by Athozus** [comment]
Thanks for reporting that's very weird indeed.

**Comment by Athozus** [comment]
It was a single line to remove the `id` when not existing, I did again the steps it looks better now. Feel free to re-open issue if you have a problem.

**Comment by Athozus** [comment]
Sorry, I've pushed on my fork instead of upstream.
